config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  devise_for :users, controllers: {
    registrations: "users/registrations",
    confirmations: "users/confirmations"
  }

  get 'home' => 'users#home', as: :home
  get 'search' => 'users#index', as: :search
  root to: 'users#home'

  resources :users, only: [:show, :index, :edit, :update, :destroy], path: ''
  resources :studios
  resources :events, only: [:new, :create, :show, :edit, :update, :destroy]
  resources :offers, only: [:new, :create, :show, :edit, :update, :destroy]
  resources :after_signup
  resources :milestones, only: [:create, :edit, :update, :destroy]
  resources :certifications, only: [:create, :edit, :update, :destroy]
  resources :practice_categories, only: [:create, :index, :edit, :update, :destroy]
  resources :specialty_categories, only: [:create, :index, :edit, :update, :destroy]

  resources :user_practice_categories, only: [:create, :destroy]
  resources :user_specialty_categories, only: [:create, :destroy]
  resources :trainer_studios, only: [:create, :destroy]
  resources :user_studios, only: [:create, :destroy]

  resources :users, only: [:show], path: '' do
    resources :events, only: [:index]
    resources :offers, only: [:index]
    resources :trainer_studios
    resources :user_studios
    get 'profile' => 'users#profile', as: :profile
    get 'bio' => 'users#bio', as: :bio
    get 'edit_bio' => 'users#edit_bio', as: :edit_bio
    get 'my_trainers' => 'users#my_trainers', as: :my_trainers
    get 'manage_events' => 'events#manage_events', as: :manage_events
    get 'manage_offers' => 'offers#manage_offers', as: :manage_offers
  end

  get '/:friendly_id', to: 'users#show'

  resources :studios do
    resources :trainer_studios
    resources :user_studios
    get 'manage_trainers' => 'studios#manage_trainers', as: :manage_trainers
  end

  post 'landing_email' => 'users#landing_email', as: :landing_email
  get 'forgot_password' => 'users#forgot_password', as: :forgot_password
  get 'welcome' => 'users#welcome', as: :welcome
  get 'verification' => 'users#verification', as: :verification
  get 'manage_users' => 'users#manage_users', as: :manage_users
end

app/models/user.rb
class User < ApplicationRecord
  extend FriendlyId
  friendly_id :username, use: [:slugged]
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and  :omniauthable
  devise :database_authenticatable, :recoverable, :rememberable, :trackable,
    :validatable, :confirmable, :registerable

  has_one_attached :avatar
  has_one_attached :cover
  has_one_attached :bio_pic

  validates :email, presence: true
  validates :email, uniqueness: true
  validates :username, uniqueness: true, presence: true, on: :update, allow_blank: false
  validates_length_of :description, maximum: 250

  has_many :user_studios
  has_many :trainer_studios
  has_many :trainer_events, foreign_key: 'trainer_id', class_name: 'Event'
  has_many :trainee_events, foreign_key: 'trainee_id', class_name: 'Event'
  has_many :trainers, -> { distinct }, through: :trainer_events
  has_many :trainees, -> { distinct }, through: :trainee_events
  has_many :offers, foreign_key: 'trainer_id'
  has_many :milestones, foreign_key: 'trainer_id'
  has_many :certifications, foreign_key: 'trainer_id'
  has_many :user_practice_categories
  has_many :user_specialty_categories

  scope :trainer, -> { where(role: 1) }
  scope :basic, -> { where(role: 0) }
  scope :admin, -> { where(role: 8) }

  geocoded_by :location
  after_validation :geocode, if: ->(obj){ obj.location.present? and obj.location_changed? }

  def self.search(search)
    where("first_name ILIKE ? OR last_name ILIKE ?", "%#{search}%", "%#{search}%")
    .trainer
  end

end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  def after_confirmation_path_for(resource_name, resource)
    # super(resource_name, resource)
    sign_in(resource) # In case you want to sign in the user
    after_signup_path(:personal)
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  def new
    super
  end

  # POST /resource
  def create
    super
  end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  def update
    super
  end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  def after_sign_up_path_for(resource)
    super(resource)
  end

  # The path used after sign up for inactive accounts.
  def after_inactive_sign_up_path_for(resource)
    :verification
  end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :load_user, only: [:show, :edit, :update, :destroy]
  before_action :load_friendly_id, only: [:bio, :edit_bio, :my_trainers]

  def show
    @events = @user.trainer_events.order("date ASC")
    @bio = @user.bio
    @events = @user.trainer_events.limit(5).order("date ASC")
  end

  def index
    if !params[:search].blank?
      @users = User.search(params[:search]).order("first_name ASC")
      @studios = Studio.search(params[:search]).order("name ASC")
    # elsif !params[:category].blank?
    #   @users = users.where(category: params[:category]).order("category ASC")
    else
      @users = User.where(role: 1).order("first_name ASC")
      @studios = Studio.all.order("name ASC")
    end
  end

  def edit
    @studios = Studio.all.order("name ASC")

    if current_user != @user
      redirect_to :index, notice: "Not authorized."
    end
  end

  def update
    if !params[:user][:avatar].nil?
      @user.avatar.attach(params[:user][:avatar])
    end

    if !params[:user][:cover].nil?
      @user.cover.attach(params[:user][:cover])
    end

    if !params[:user][:bio_pic].nil?
      @user.bio_pic.attach(params[:user][:bio_pic])
    end

    if @user.update_attributes(user_params)
      redirect_to user_url(@user), notice: "Account updated!"
    else
      render :edit
    end
  end

  def destroy
  end

  def home
  end

  def welcome
  end

  def my_trainers
  end

  def landing_email
    SendGridService::Email.new(
      'trainrbio@gmail.com',
      'trainrbio@gmail.com',
      "#{current_user.email} sent a message from the prelaunch site!",
      'text/plain',
      params[:comment],
    ).send_email

    # UserMailer.landing_email(body).deliver_later

    redirect_to root_url, notice: "Thanks for the feedback!"
  end

  def forgot_password
  end

  def verification
  end

  def profile
    @events = @user.trainer_events.limit(5).order("date ASC")
  end

  def bio
    @milestones = @user.milestones.order("year ASC")
    @certifications = @user.certifications.order("start_date ASC")
    @practices = UserPracticeCategory.where(user_id: @user.id).includes(:practice_category).sort_by { |p| p.practice_category.name }
    @specialties = UserSpecialtyCategory.where(user_id: @user.id).includes(:specialty_category).sort_by { |s| s.specialty_category.name }
  end

  def edit_bio
    @user = current_user
    @mypractices = UserPracticeCategory.where(user_id: @user.id).includes(:practice_category).sort_by { |p| p.practice_category.name }
    @myspecialties = UserSpecialtyCategory.where(user_id: @user.id).includes(:specialty_category).sort_by { |s| s.specialty_category.name }
    @milestones = @user.milestones.order("year ASC")
    @milestone = Milestone.new
    @certifications = @user.certifications.order("start_date ASC")
    @certification = Certification.new
    @practices = PracticeCategory.all.order("name ASC")
    @specialties = SpecialtyCategory.all.order("name ASC")
  end

  def manage_users
    @users = User.all.order("email ASC")
  end

  private

  def load_user
    @user = User.friendly.find(params[:id])
  end

  def load_friendly_id
    @user = User.friendly.find(params[:user_id])
  end

  def user_params
    params.require(:user).permit(
      :email, :username, :phone, :location, :first_name, :last_name, :img_url,
      :instagram_url, :facebook_url, :website_url, :tik_tok_url, :description,
      :password, :password_confirmation, :role, :latitude, :longitude, :bio,
      :headline
    )
  end
end

app/views/users/admin.html.erb
<% if current_user && current_user.role == 8 %>
  <%= render 'layouts/navbar_search_results_logged_out' %>
  <p class="my-5">Welcome to the admin panel!</p>
  <%= render 'layouts/footer_admin' %>
<% else %>
  <%= render 'layouts/navbar_search_results_logged_out' %>
  <p class="my-5">Sorry, this page is not for you</p>
  <%= link_to "Go Home", home_url, class:'btn btn-sm btn-outline-info btn-block round-btn' %>
  <% if current_user.role == 0 %>
    <%= render 'layouts/footer_trainee' %>
  <% else %>
    <%= render 'layouts/footer_trainer' %>
  <% end %>
<% end %>

app/views/users/bio.html.erb
<% if !current_user %>
  <%= render 'layouts/navbar_profile_logged_out' %>
<% else %>
  <%= render 'layouts/navbar_profile' %>
<% end %>

<div class="grey-bottom-border"></div>

<div class="container">
  <div class="row my-1 text-center">
    <div class="col-4" style="secondary-nav">
      <%= link_to user_url(@user), class: "secondary-link" do %>
        <p class="my-2">PROFILE</p>
      <% end %>
    </div>
    <div class="col-4" style="secondary-nav">
      <%= link_to user_offers_url(@user), class: "secondary-link" do %>
        <p class="my-2">OFFERINGS</p>
      <% end %>
    </div>
    <div class="col-4" style="secondary-nav active">
      <%= link_to user_bio_url(@user), class: "secondary-link active" do %>
        <u><p class="my-2">BIO</p></u>
      <% end %>
    </div>
  </div>
</div>

<div class="container">
  <div class="row mb-2 text-center">
    <div class="col-12">
      <% if @user.bio_pic.attachment.nil? %>
        <%= image_tag('upload.png', class:'btn-block')%>
      <% else %>
        <%= image_tag(@user.bio_pic.service_url, class:'btn-block')%>
      <% end %>
    </div>
  </div>

<!--
  <div class="row my-1 text-center">
    <div class="col-1"></div>
    <div class="col-1"></div>
    <div class="col-8"> ● ○ ○ </div>
    <div class="col-1"></div>
    <div class="col-1"></div>
  </div> -->

  <% if current_user && current_user == @user %>
        <%= link_to "Edit Bio Page", user_edit_bio_url(current_user), class: "btn btn-block btn-sm btn-info" %>
      <hr>
  <% end %>

</div>

<div class="container mb-5">
  <% if !@user.bio.nil? %>
    <% if !@user.bio.empty? %>
      <div class="row mb-2 mx-1">
        <div class="col-12"><p><%= @user.bio %></p></div>
      </div>
    <% end %>
  <% end %>

  <% if !@practices.nil? && !@specialties.nil? %>
    <% if !@practices.empty? || !@specialties.empty? %>
      <hr>
      <!-- <div class="color-bottom-border my-2"></div> -->
    <% end %>
  <% end %>
  <% if !@practices.nil? %>
    <% if !@practices.empty? %>
      <div class="my-3">
        <div class="row">
          <div class="col-12"><h3>I Teach:</h3></div>
        </div>
        <div class="row">
          <div class="col-12">
            <% @practices.each do |practice| %>
              <div class="badge badge-success"><%= practice.practice_category.name %></div>
            <% end %>
          </div>
        </div>
      </div>
    <% end %>
  <% end %>
  <% if !@specialties.nil? %>
    <% if !@specialties.empty? %>
      <div class="my-3">
        <div class="row">
          <div class="col-12"><h3>I'm Known For:</h3></div>
        </div>
        <div class="row">
          <div class="col-12">
            <% @specialties.each do |specialty| %>
                <div class="badge badge-success"><%= specialty.specialty_category.name %></div>
            <% end %>
          </div>
        </div>
      </div>
    <% end %>
  <% end %>



  <% if !@milestones.nil? %>
    <% if !@milestones.empty? %>
      <hr>
      <!-- <div class="color-bottom-border mt-3 mb-3"></div> -->
      <div class="timeline my-3">
        <div class="row mb-2">
          <div class="col-12"><h3>Experience & Milestones</h3></div>
        </div>
          <% @milestones.each do |milestone| %>
            <div class="row">
              <div class="col-1">○</div>
              <div class="col-2"><p><%= milestone.year %></p></div>
              <div class="col-7"><p><%= milestone.milestone %></p></div>
              <div class="col-1"><!-- if verified, display checkmark --></div>
            </div>
          <% end %>
      </div>
    <% end %>
  <% end %>

  <% if !@certifications.nil? %>
    <% if !@certifications.empty? %>
      <hr>
      <div class="row mb-2">
        <div class="col-12"><h3>Certifications</h3></div>
      </div>
      <% @certifications.each do |certification| %>
        <div class="row mt-3">
          <div class="col-2 mt-1">
            <% if !certification.cert_pic.attachment.nil? %>
              <%= image_tag(certification.cert_pic.service_url, height: 27, width: 27, class:'round-btn')%>
            <% end %>
          </div>
          <div class="col-10 px-2 text-left">
            <% if !certification.name.nil? || !certification.level.nil? %>
              <p><%= "#{certification.name + ' ' + certification.level}" %><br/>
            <% else %>
              <p>Cert name & level missing<br/>
            <% end %>
            <% if !certification.website_url.nil? %>
              <% if !certification.website_url.empty? %>
                <%= link_to "#{certification.accreditor}", "https://#{certification.website_url}", target: :_blank,  class: "" %><br/>
              <% end %>
            <% end %>
            <% if !certification.description.nil? %>
              <%= "#{certification.description}"%></p>
            <% end %>
          </div>
        </div>
      <% end %>
    <% end %>
  <% end %>

</div>

<%= render 'layouts/footer' %>

app/views/users/index.html.erb
<% if !current_user %>
  <%= render 'layouts/navbar_search_results_logged_in' %>
  <%= render 'layouts/footer' %>
<% else %>
  <%= render 'layouts/navbar_search_results_logged_in' %>
  <%= render 'layouts/footer' %>
<% end %>

<hr>
<div class="container text-center">

  <% if !params[:search].blank? %>
    <% if !@users.empty? || @studios.empty? %>
    <div class="row">
      <div class="col-12">
        <p class="text-left text-primary"><%= @users.length + @studios.length %> Result(s)</p>
      </div>
    </div>
    <% end %>
  <% end %>

  <div class="row mt-2">
    <div class="col-2"></div>
      <div class="col-8">
      <ul class="nav nav-pills justify-content-center" role="tablist" id="searchTab">
        <li class="nav-item">
          <a class="schedule week-toggle mr-1 ml-1 active" id="trainers-tab" href="#trainers" data-toggle="pill" role="tab" aria-controls="trainers" aria-selected="true">People</a>
        </li>
        <p class="nav-splitter mt-1">∞</p>
        <li class="nav-item">
          <a class="schedule week-toggle mr-1 ml-1" id="studios-tab" href="#studios" data-toggle="pill" role="tab" aria-controls="studios" aria-selected="false">Studios</a>
        </li>
      </ul>
    </div>
    <div class="col-2"></div>
  </div>

  <div class="tab-content clearfix mb-5">
    <div class="tab-pane active" id="trainers" role="tabpanel" aria-labelledby="trainers-tab">
      <div class="grey-bottom-border"></div>
      <% @users.each do |trainer| %>
        <div class="row mt-3 ml-1">
          <div class="col-2 ">
            <% if trainer.avatar.attachment.nil? %>
              <%= image_tag('user.svg', height: 42, width: 42, class:'round-btn')%>
            <% else %>
              <%= image_tag(trainer.avatar.service_url, height: 42, width: 42, class:'round-btn')%>
            <% end %>
          </div>
          <div class="col-6 mx-2 text-left">
            <%= link_to user_url(trainer) do %>
              <div class="row ml-1">
                <% if !trainer.first_name.nil? || !trainer.last_name.nil? %>
                  <p class=""><%= "#{trainer.first_name + ' ' + trainer.last_name}"%><br/>
                <% else %>
                  <p class="">-<br/>
                <% end %>
                <% if !trainer.headline.nil? %>
                  <%= "#{trainer.headline}"%></p>
                <% else %>
                  -</p>
                <% end %>
              </div>
            <% end %>
          </div>
          <div class="col-3 my-auto text-right">
            <p class=""><%= trainer.location %></p>
          </div>
        </div>
        <div class="grey-bottom-border"></div>
      <% end %>
      <% if @users.empty? %>
        <div class="col-12">
          <p class="mt-3 mb-3">No humans found.</p>
        </div>
      <% end %>
    </div>

    <div class="tab-pane" id="studios" role="tabpanel" aria-labelledby="studios-tab">
        <div class="text-center studio-q">Don't see your studio? <%= link_to "Add New", new_studio_url %></div>
      <div class="grey-bottom-border"></div>
      <% @studios.each do |studio| %>
        <div class="row mt-3 mx-2">
          <div class="col-2 my-auto">
            <% if studio.avatar.attachment.nil? %>
              <%= image_tag('search.svg', height: 42, width: 42, class:'round-btn')%>
            <% else %>
              <%= image_tag(studio.avatar.service_url, height: 42, width: 42, class:'round-btn')%>
            <% end %>
          </div>
          <div class="col-6 my-auto text-left">
            <% if !studio.name.nil? %>
              <p class=""><%= link_to "#{studio.name}", studio_url(studio) %></p>
            <% end %>
          </div>
          <div class="col-4 my-auto text-right">
            <% if !studio.location.nil? %>
              <p class=""><%= studio.location %></p>
            <% end %>
            <% if !studio.phone.nil? %>
              <p class=""><%= studio.phone %></p>
            <% end %>
          </div>
        </div>
        <div class="grey-bottom-border"></div>
      <% end %>
      <% if @studios.empty? %>
        <div class="col-12">
          <p class="mt-3 mb-3">No studios found.</p>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/users/manage_users.html.erb
<% if current_user && current_user.role == 8 %>
  <div class="container text-center">
    <ol class="mt-5">
      <h5 class="mb-3">Mailing List</h5>
      <% @users.each do |user| %>
        <li><%= link_to user.email, user_url(user), class:"" %></li>
      <% end %>
    </ol>
  <div>
  <%= render 'layouts/footer_admin' %>
<% else %>
  <%= render 'layouts/navbar_search_results_logged_out' %>
  <p class="my-5">Sorry, this page is not for you</p>
  <%= link_to "Go Home", home_url, class:'btn btn-sm btn-outline-info btn-block round-btn' %>
  <% if current_user.role == 0 %>
    <%= render 'layouts/footer_trainee' %>
  <% else %>
    <%= render 'layouts/footer_trainer' %>
  <% end %>
<% end %>

app/views/users/show.html.erb
<% if !current_user %>
  <%= render 'layouts/navbar_profile_logged_out' %>
<% else %>
  <%= render 'layouts/navbar_profile' %>
<% end %>

<div class="grey-bottom-border"></div>

<div class="container">
  <div class="row my-1 text-center">
    <div class="col-4" style="secondary-nav active">
      <%= link_to user_url(@user), class: "secondary-link active" do %>
        <u><p class="my-2">PROFILE</p></u>
      <% end %>
    </div>
    <div class="col-4" style="secondary-nav">
      <%= link_to user_offers_url(@user), class: "secondary-link" do %>
        <p class="my-2">OFFERINGS</p>
      <% end %>
    </div>
    <div class="col-4" style="secondary-nav">
      <%= link_to user_bio_url(@user), class: "secondary-link" do %>
        <p class="my-2">BIO</p>
      <% end %>
    </div>
  </div>
</div>


<!-- <div class="container text-center">
  <div class="row">
    <div class="col-12"> -->
      <!-- change below to "image_tag(@user.cover_img_url, class: "offer-pic", height: 84, width: 226.7)"  -->
      <% if @user.cover.attachment.nil? %>
        <%= image_tag('upload.png', class:'cover-img btn-block') %>
      <% else %>
        <%= image_tag(@user.cover.service_url, class:'cover-img btn-block')%>
      <% end %>
    <!-- </div>
  </div>
</div> -->

<div class="container text-center">
  <div class="row">
    <div class="col ml-3">
      <!-- change below to "image_tag(@user.profile_img_url, class: "profile-pic")"  -->
      <% if @user.avatar.attachment.nil? %>
        <%= image_tag('profile.png', class:'profile-pic round-btn btn-block')%>
      <% else %>
        <%= image_tag(@user.avatar.service_url, class:'profile-pic round-btn btn-block')%>
      <% end %>
    </div>
    <div class="col mr-3">
      <div class="row d-flex justify-content-center user-name-lg mt-3"><%= @user.first_name %></div>
      <div class="row d-flex justify-content-center user-name-lg"><%= @user.last_name %></div>
      <div class="row d-flex justify-content-center user-headline mt-2"><%= @user.headline %></div>
      <div class="row d-flex justify-content-center user-location mt-1 mb-2"><%= @user.location %></div>

      <div class="row d-flex justify-content-center mx-1">
        <% if !@user.website_url.nil? %>
          <% if !@user.website_url.empty? %>
            <%= link_to image_tag('website.png', height: 20, width: 20, class:'mx-2'), "https://#{@user.website_url}" %>
          <% end %>
        <% end %>
        <% if !@user.instagram_url.nil? %>
          <% if !@user.instagram_url.nil? %>
            <%= link_to image_tag('instagram.svg', height: 20, width: 20, class:'mx-2'), "https://www.instagram.com/#{@user.instagram_url}"%>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>


  <% if current_user && current_user == @user %>
      <div class="row d-flex justify-content-center mt-3 mx-3">
        <%= link_to "Edit Profile", edit_user_url(current_user), class: "btn btn-block btn-sm btn-info" %>
      </div>
  <% end %>


  <hr>

  <div class="row">
    <div class="col-1"></div>
    <div class="col-10 user-description"><p><%= @user.description %></p></div>
    <div class="col-1"></div>
  </div>

  <hr>

  <div class="row">
    <div class="col-12"><i>Upcoming</i></div>
  </div>
  <div class="row">
    <div class="col-8"></div>
    <div class="col-4 text-right"><u><%= link_to "Full Schedule", user_events_url(@user),  class: "footer-link" %></u></div>
  </div>
  <% if @events.empty?  %>
    <div class="row my-3">
      <div class="col-2"></div>
      <div class="col-8"><span class="schedule date"> No classes or workshops this week. </span></div>
      <div class="col-2"></div>
    </div>
  <% else %>
    <% $previous_date = 0 %>
    <% @events.each do |event| %>
        <% if event.date != @previous_date %>
          <div class="row mt-1">
            <div class="col-12 text-left">
              <span class="schedule date"><%= event.date.strftime('%a %_m/%-d') %><br/></span>
            </div>
          </div>
          <% @previous_date = event.date %>
        <% end %>
        <div class="row">
          <div class="col-3 text-center"><span class="schedule time"><%= event.start_time.strftime('%l:%M %p') %></span></div>
          <div class="col-6 text-center"><span class="schedule session-name"><%= event.title %></span></div>
          <div class="col-3 text-right"><span class="schedule studio-name">
            <% if event.location[0..3] == "http" || event.location[0..4] == "https" || event.location[0..2] == "www" %>
              <%= link_to event.location.truncate(13, omission: '...'), "http://#{event.location.sub(%r!^https?://!i, '')}", target: "_blank"  %>
            <% else %>
              <%= event.location %>
            <% end %>
          </span></div>
        </div>
    <% end %>
  <% end %>

  <div class="row d-flex justify-content-center mt-3 mx-3">
    <%= link_to "Book & Pay", "https://trustfollo.com/#{@user.instagram_url}", class: "btn btn-block btn-sm btn-info" %>
  </div>

  <hr class='mb-5'>

</div>

<%= render 'layouts/footer' %>

app/views/users/welcome.html.erb
<div class="container text-center">
  <div class="row mt-5 mb-5">
    <div class="col-1"></div>
    <div class="col-10">
      <%= render 'layouts/navbar_home_logged_out' %>

      <p class="text-primary mb-3"><%= flash[:notice] %></p>
      <p class="text-primary mb-3"><%= flash[:alert] %></p>

      <p class="auth">Welcome to mvmt.bio!</p>
    </div>
  </div>
  <div class="col-1"></div>

  <div class="row">
    <div class="col-4"></div>
    <div class="col-4">
      <%= link_to "Enter", home_url, class:"btn btn-info btn-block" %>
    </div>
    <div class="col-4"></div>
  </div>

  <div class="row">
    <p class="branding footer mt-5 ml-auto mr-auto">mvmt.bio 2020</p>
  </div>
</div>