config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  devise_for :users, controllers: {
    registrations: "users/registrations",
    confirmations: "users/confirmations"
  }

  get 'home' => 'users#home', as: :home
  get 'search' => 'users#index', as: :search
  root to: 'users#home'

  resources :users, only: [:show, :index, :edit, :update, :destroy], path: ''
  resources :studios
  resources :events, only: [:new, :create, :show, :edit, :update, :destroy]
  resources :offers, only: [:new, :create, :show, :edit, :update, :destroy]
  resources :after_signup
  resources :milestones, only: [:create, :edit, :update, :destroy]
  resources :certifications, only: [:create, :edit, :update, :destroy]
  resources :practice_categories, only: [:create, :index, :edit, :update, :destroy]
  resources :specialty_categories, only: [:create, :index, :edit, :update, :destroy]

  resources :user_practice_categories, only: [:create, :destroy]
  resources :user_specialty_categories, only: [:create, :destroy]
  resources :trainer_studios, only: [:create, :destroy]
  resources :user_studios, only: [:create, :destroy]

  resources :users, only: [:show], path: '' do
    resources :events, only: [:index]
    resources :offers, only: [:index]
    resources :trainer_studios
    resources :user_studios
    get 'profile' => 'users#profile', as: :profile
    get 'bio' => 'users#bio', as: :bio
    get 'edit_bio' => 'users#edit_bio', as: :edit_bio
    get 'my_trainers' => 'users#my_trainers', as: :my_trainers
    get 'manage_events' => 'events#manage_events', as: :manage_events
    get 'manage_offers' => 'offers#manage_offers', as: :manage_offers
  end

  get '/:friendly_id', to: 'users#show'

  resources :studios do
    resources :trainer_studios
    resources :user_studios
    get 'manage_trainers' => 'studios#manage_trainers', as: :manage_trainers
  end

  post 'landing_email' => 'users#landing_email', as: :landing_email
  get 'forgot_password' => 'users#forgot_password', as: :forgot_password
  get 'welcome' => 'users#welcome', as: :welcome
  get 'verification' => 'users#verification', as: :verification
  get 'manage_users' => 'users#manage_users', as: :manage_users
end

app/models/offer.rb
class Offer < ApplicationRecord
  validates :title, :description, :location, :cost, :trainer_id, presence: true

  has_one_attached :avatar

  belongs_to :trainers, foreign_key: 'trainer_id', class_name: 'User', optional: true

  scope :hidden, -> { where(status: 1) }
  scope :active, -> { where(status: 0) }

  geocoded_by :location
  after_validation :geocode, if: ->(obj){ obj.location.present? and obj.location_changed? }
end

app/controllers/offers_controller.rb
class OffersController < ApplicationController
  before_action :load_offer, only: [:show, :edit, :update, :destroy]

  def index
    @user = User.friendly.find(params[:user_id])
    @offers = @user.offers
  end

  def show
    @user = current_user
  end

  def manage_offers
    @user = current_user
    @offer = @user.offers #need id of specific offer
  end

  def new
    @offer = Offer.new
  end

  def create
    @offer = Offer.new(offer_params)
    attach_image

    if @offer.save
      redirect_to user_offers_path(@offer.trainer_id), notice: "Offer created!"
    else
      render :new
    end
  end

  def edit
  end

  def update
    attach_image

    if @offer.update_attributes(offer_params)
      redirect_to user_offers_url(@offer.trainer_id), notice: "Offer details updated!"
    else
      render :edit
    end
  end

  def destroy
    @offer.destroy
    redirect_to user_offers_url(@offer.trainer_id), notice: "Offer deleted."
  end

  private

  def load_offer
    @offer = Offer.find(params[:id])
  end

  def offer_params
    params.require(:offer).permit(
      :title, :description, :duration, :start_time, :date, :location, :latitude,
      :longitude, :trainer_id, :cost, :booking_url, :status, :other
    )
  end

  def attach_image
    if !params[:offer][:avatar].nil?
      @offer.avatar.attach(params[:offer][:avatar])
    end
  end
end

app/views/offers/_form.html.erb
<!-- < Add/Edit Offering -->
<div class="container my-5">
  <%= form_for(@offer) do |f| %>
    <% if @offer.errors.any? %>
      <div id="error_explanation">
        <h5><%= pluralize(@offer.errors.count, "error") %> prohibited change!</h5>
        <ul>
        <% @offer.errors.full_messages.each do |msg| %>
          <li class="error"><%= msg %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <div class="row mb-3">
      <div class="col-1"></div>
      <div class="col-3"><%= f.label "Title*", class: "" %></div>
      <div class="col-7"><%= f.text_field :title, placeholder: "", class: "btn-block no-border color-bottom-border", required: true %></div>
      <div class="col-1"></div>
    </div>

    <!-- Offering Type -->

    <div class="row mb-1">
      <div class="col-1"></div>
      <div class="col-10"><%= f.label "Short Description*", class: "" %></div>
      <div class="col-1"></div>
    </div>
    <div class="row mb-3">
      <div class="col-1"></div>
      <div class="col-10"><%= f.text_area :description, placeholder: "", class: "btn-block no-border color-bottom-border", required: true %></div>
      <div class="col-1"></div>
    </div>

    <div class="row mb-3">
      <div class="col-1"></div>
      <div class="col-3"><%= f.label "Duration", class: "" %></div>
      <div class="col-7"><%= f.text_field :duration, placeholder: "", class: "btn-block no-border color-bottom-border", required: true %></div>
      <div class="col-1"></div>
    </div>

    <!-- Date/Time -->

    <div class="row mb-3">
      <div class="col-1"></div>
      <div class="col-3"><%= f.label "Location*", class: "" %></div>
      <div class="col-7"><%= f.text_field :location, placeholder: "", class: "btn-block no-border color-bottom-border", required: true, id: :autocomplete_address %></div>
      <div class="col-1"></div>
    </div>

    <div class="row mb-3">
      <div class="col-1"></div>
      <div class="col-3"><%= f.label "Cost*", class: "" %></div>
      <div class="col-7"><%= f.text_field :cost, placeholder: "", class: "btn-block no-border color-bottom-border", required: true %></div>
      <div class="col-1"></div>
    </div>

    <div class="row mb-1">
      <div class="col-1"></div>
      <div class="col-10"><%= f.label "Other Info", class: "" %></div>
      <div class="col-1"></div>
    </div>
    <div class="row mb-3">
      <div class="col-1"></div>
      <div class="col-10"><%= f.text_area :other, placeholder: "", class: "btn-block no-border color-bottom-border" %></div>
      <div class="col-1"></div>
    </div>

    <div class="row mb-1">
      <div class="col-1"></div>
      <div class="col-10"><%= f.label "Booking URL or Contact Email", class: "" %></div>
      <div class="col-1"></div>
    </div>
    <div class="row mb-3">
      <div class="col-1"></div>
      <div class="col-10"><%= f.text_field :booking_url, placeholder: "", class: "btn-block no-border color-bottom-border" %></div>
      <div class="col-1"></div>
    </div>

    <div class="row mb-1">
      <div class="col-1"></div>
      <div class="col-10"><%= f.label "Cover Photo*", class: "" %></div>
      <div class="col-1"></div>
    </div>
    <div class="row mb-3">
      <div class="col-1"></div>
      <div class="col-10"><%= f.file_field :avatar, class: "no-border", required: true %></div>
      <div class="col-1"></div>
    </div>

    <%= f.hidden_field :trainer_id, value: current_user.id %>

    <!--
    Hide Offering
    Delete Offering
    -->

    <div class="row">
      <div class="col-8"></div>
      <div class="col-3">
        <%= f.submit 'Save', class: 'btn btn-info' %>
      </div>
      <div class="col-1"></div>
    </div>
  <% end %>
</div>

<%= javascript_include_tag 'autocomplete', 'data-turbolinks-track': 'reload' %>

app/views/offers/edit.html.erb
<%= render 'layouts/navbar_edit' %>

<%= render 'form' %>

<div class="container my-3" id="practice">
  <div class="row mb-3">
    <div class="col-3"></div>
    <div class="col-6">
      <%= button_to "Delete Offer", { action: "destroy", controller: "offers", id: @offer.id },
      method: :delete, data: { confirm: "Are you sure?" },
      class: "btn btn-sm btn-danger" %>
    </div>
    <div class="col-3"></div>
  </div>
</div>

app/views/offers/index.html.erb
<% if !current_user %>
  <%= render 'layouts/navbar_profile_logged_out' %>
<% else %>
  <%= render 'layouts/navbar_profile' %>
<% end %>

<div class="grey-bottom-border"></div>

<div class="container">
  <div class="row my-1 text-center">
    <div class="col-4" style="secondary-nav">
      <%= link_to user_url(@user), class: "secondary-link" do %>
        <p class="my-2">PROFILE</p>
      <% end %>
    </div>
    <div class="col-4" style="secondary-nav active">
      <%= link_to user_offers_url(@user), class: "secondary-link active" do %>
        <u><p class="my-2">OFFERINGS</p></u>
      <% end %>
    </div>
    <div class="col-4" style="secondary-nav">
      <%= link_to user_bio_url(@user), class: "secondary-link" do %>
        <p class="my-2">BIO</p>
      <% end %>
    </div>
  </div>
  <% if current_user && current_user == @user %>
    <%= link_to "+ Add New Offering", new_offer_url,  class: "btn btn-sm btn-info btn-block mb-2" %>
  <% end %>
</div>

<div class="container mb-5 text-center">
  <% if @offers.empty? %>
    <div class="row mt-4 mb-4">
      <div class="col-2"></div>
      <div class="col-8"><span class="schedule date"> No offers to show. </span></div>
      <div class="col-2"></div>
    </div>
  <% else %>
    <% @offers.each do |offer| %>
      <figure my-2 style="border-style: solid; border-width: 1px;">
        <div class="row">
          <div class="col-12">
            <% if offer.avatar.attachment.nil? %>
              <%= link_to image_tag("cover.jpg", class: "offer-pic btn-block"), offer_url(offer) %>
            <% else %>
              <%= link_to image_tag(offer.avatar.service_url, class: "offer-pic btn-block"), offer_url(offer) %>
            <% end %>
          </div>
        </div>
        <figcaption>
          <div class="row">
            <div class="col-2">
              <% if current_user && current_user == @user %>
                <% if offer.status == 1 %>
                  <%= image_tag('private.svg', height: 11, width: 11, class:'') %>
                <% end %>
              <% end %>
            </div>
            <div class="col-8"><%= offer.title %></div>
            <div class="col-2">
              <% if current_user && current_user == @user %>
                <%= link_to image_tag('edit.png', height: 11, width: 11, class:''), edit_offer_url(offer) %>
              <% end %>
            </div>
          </div>
        </figcaption>
      </figure>
    <% end %>
  <% end %>
</div>

<%= render 'layouts/footer' %>

app/views/offers/new.html.erb
<%= render 'layouts/navbar_add_offer' %>

<%= render 'form' %>

app/views/offers/old_index.html.erb
<%= render 'layouts/navbar' %>
<!-- secondary navbar, offerings active -->

<div class="container text-center"><%= flash[:notice] %></div>

<div class="container">
  <% if !@offers.empty? %>
    <% @offers.each do |offer| %>
      <div class="row text-center">
        <div class="col-12">
          <figure>
            <!-- change below to "link_to image_tag(offer.coverimg_url, class: "offer-pic"), offer.url"  -->
            <%= link_to image_tag('cover.jpg', height: 31.5, width: 85, class:''), show_offer_url %>
            <figcaption><%= offer.title %></figcaption>
          </figure>
        </div>
      </div>
    <% end %>
  <% elsif current_user == @user %>
    <div class="row text-center">
      <div class="col-12">
        <%= link_to "Add New Offer", new_offer_url %>
      </div>
    </div>
  <% end %>
</div>

<% if current_user && current_user.role == 1 %>
	<%= render 'layouts/footer_trainer' %>
<% else %>
	<%= render 'layouts/footer_trainee' %>
<% end %>

app/views/offers/show.html.erb
<nav class="navbar navbar-light mt-3 mb-3">
  <div class="col-3">
    <%= link_to image_tag("back.jfif", height:'13', width:'18' ), :back %>
  </div>
  <div class="col-6 text-center">
  </div>
  <div class="col-3"></div>
</nav>

<div class="container">
  <div class="row mb-3">
    <div class="col-12">
      <% if @offer.avatar.attachment.nil? %>
        <%= image_tag("cover.jpg", class: "btn-block") %>
      <% else %>
        <%= image_tag(@offer.avatar.service_url, class: "btn-block") %>
      <% end %>
    </div>
  </div>
  <hr>
</div>



<div class="container">
  <div class="row">
    <div class="col-12 offer-title"><h2><%= @offer.title %></h2></div>
  </div>
  <div class="row">
    <div class="col-12 offer-location"><h2><%= @offer.location %></h2></div>
  </div>
  <div class="row text-center">
    <div class="col-12"><p><%= @offer.category %></p></div>
  </div>
  <div class="row text-center">
    <div class="col-12"><p><%= @offer.description %></p></div>
  </div>

  <% if !@offer.date.nil? %> <!-- if it exists/isTrue (if it contains valuable data instead of loose pointer)-->
    <div class="row my-1">
      <div class="col-12"><h3> Date/Time </h3></div>
    </div>
    <div class="row mb-3">
      <div class="col-1"></div>
      <div class="col-10">
        <p> <%= @offer.date %> </p>
      </div>
      <div class="col-1"></div>
    </div>
  <% end %>

  <% if !@offer.expectations.blank? %> <!-- if it exists/isTrue (if it contains valuable data instead of loose pointer)-->
    <div class="row my-1">
      <div class="col-12"><h3> What to Expect </h3></div>
    </div>
    <div class="row mb-3">
      <div class="col-1"></div>
      <div class="col-10">
        <p> <%= @offer.expectations %> </p>
      </div>
      <div class="col-1"></div>
    </div>
  <% end %>

  <% if !@offer.highlights.blank? %> <!-- if it exists/isTrue (if it contains valuable data instead of loose pointer)-->
    <div class="row my-1">
      <div class="col-12"><h3> Highlights </h3></div>
    </div>
    <div class="row mb-3">
      <div class="col-1"></div>
      <div class="col-10">
        <p> <%= @offer.highlights %> </p>
      </div>
      <div class="col-1"></div>
    </div>
  <% end %>

  <% if !@offer.duration.nil? %> <!-- if it exists/isTrue (if it contains valuable data instead of loose pointer)-->
    <div class="row my-1">
      <div class="col-12"><h3> Duration </h3></div>
    </div>
    <div class="row mb-3">
      <div class="col-1"></div>
      <div class="col-10">
        <p> <%= @offer.duration %> </p>
      </div>
      <div class="col-1"></div>
    </div>
  <% end %>

  <% if !@offer.cost.nil? %> <!-- if it exists/isTrue (if it contains valuable data instead of loose pointer)-->
    <div class="row my-1">
      <div class="col-12"><h3> Cost </h3></div>
    </div>
    <div class="row mb-3 text-center">
      <div class="col-1"></div>
      <div class="col-10">
        <p> <%= @offer.cost %> </p>
      </div>
      <div class="col-1"></div>
    </div>
  <% end %>

  <% if !@offer.other.blank? %> <!-- if it exists/isTrue (if it contains valuable data instead of loose pointer)-->
    <div class="row my-1">
      <div class="col-12"><h3> Other Info </h3></div>
    </div>
    <div class="row mb-3">
      <div class="col-1"></div>
      <div class="col-10">
        <p> <%= @offer.other %> </p>
      </div>
      <div class="col-1"></div>
    </div>
  <% end %>

  <div class="row my-1">
    <div class="col-3"></div>
    <div class="col-6"><%= link_to "Contact & Book", @offer.booking_url,  class: "btn btn-info btn-sm btn-block" %></div>
    <div class="col-3"></div>
  </div>

</div>

<%= render 'layouts/footer' %>