config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  devise_for :users, controllers: {
    registrations: "users/registrations",
    confirmations: "users/confirmations"
  }

  get 'home' => 'users#home', as: :home
  get 'search' => 'users#index', as: :search
  root to: 'users#home'

  resources :users, only: [:show, :index, :edit, :update, :destroy], path: ''
  resources :studios
  resources :events, only: [:new, :create, :show, :edit, :update, :destroy]
  resources :offers, only: [:new, :create, :show, :edit, :update, :destroy]
  resources :after_signup
  resources :milestones, only: [:create, :edit, :update, :destroy]
  resources :certifications, only: [:create, :edit, :update, :destroy]
  resources :practice_categories, only: [:create, :index, :edit, :update, :destroy]
  resources :specialty_categories, only: [:create, :index, :edit, :update, :destroy]

  resources :user_practice_categories, only: [:create, :destroy]
  resources :user_specialty_categories, only: [:create, :destroy]
  resources :trainer_studios, only: [:create, :destroy]
  resources :user_studios, only: [:create, :destroy]

  resources :users, only: [:show], path: '' do
    resources :events, only: [:index]
    resources :offers, only: [:index]
    resources :trainer_studios
    resources :user_studios
    get 'profile' => 'users#profile', as: :profile
    get 'bio' => 'users#bio', as: :bio
    get 'edit_bio' => 'users#edit_bio', as: :edit_bio
    get 'my_trainers' => 'users#my_trainers', as: :my_trainers
    get 'manage_events' => 'events#manage_events', as: :manage_events
    get 'manage_offers' => 'offers#manage_offers', as: :manage_offers
  end

  get '/:friendly_id', to: 'users#show'

  resources :studios do
    resources :trainer_studios
    resources :user_studios
    get 'manage_trainers' => 'studios#manage_trainers', as: :manage_trainers
  end

  post 'landing_email' => 'users#landing_email', as: :landing_email
  get 'forgot_password' => 'users#forgot_password', as: :forgot_password
  get 'welcome' => 'users#welcome', as: :welcome
  get 'verification' => 'users#verification', as: :verification
  get 'manage_users' => 'users#manage_users', as: :manage_users
end

app/models/studio.rb
class Studio < ApplicationRecord
  validates :name, :location, presence: true

  has_one_attached :avatar

  has_many :user_studios
  has_many :trainer_studios

  geocoded_by :location
  after_validation :geocode, if: ->(obj){ obj.location.present? and obj.location_changed? }

  def self.search(search)
    where("name ILIKE ?", "%#{search}%")
    # .user
  end
end

app/controllers/studios_controller.rb
class StudiosController < ApplicationController
  before_action :load_studio, only: [:show, :edit, :update, :destroy]

  def new
    @studio = Studio.new
  end

  def create
    @studio = Studio.new(studio_params)
    attach_image

    if @studio.save
      session[:studio_id] = @studio.id
      redirect_to studio_url(@studio.id), notice: "Studio created!"
    else
      render :new
    end
  end

  def show
  end

  def index
    @studios = Studio.all
  end

  def edit
    @trainers = User.where(role: 1).order("first_name ASC")
  end

  def update
    if !params[:studio][:avatar].nil?
      attach_image
    end

    if @studio.update_attributes(studio_params)
      redirect_to studio_path(@studio), notice: "Studio details updated!"
    else
      render :edit
    end
  end

  def destroy
    @studio.destroy
    redirect_to studios_path, notice: "Studio deleted!"
  end

  private

  def load_studio
    @studio = Studio.find(params[:id])
  end

  def studio_params
    params.require(:studio).permit(
      :name, :phone, :location, :img_url, :website_url, :username, :latitude,
      :longitude
    )
  end

  def attach_image
    @studio.avatar.attach(params[:studio][:avatar])
  end
end

app/views/studios/_form.html.erb
<!-- < Add/Edit Studio -->
<div class="container my-5 text-center">
  <p class="text-primary mb-3"><%= flash[:notice] %></p>
  <%= flash[:alert] %>

  <%= form_for(@studio) do |f| %>
    <% if @studio.errors.any? %>
      <div id="error_explanation">
        <h5><%= pluralize(@studio.errors.count, "error") %> prohibited change!</h5>
        <ul>
          <% @studio.errors.full_messages.each do |msg| %>
            <li class="error"><%= msg %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="row mb-3">
      <div class="col-1"></div>
      <div class="col-10">
        <div class="form-group">
          <h6>Studio Username*:</h6>
          <br/>
          <%= f.text_field :username, placeholder: "CoreStudio", class: "form-control no-border color-bottom-border", required: true %>
        </div>
       </div>
       <div class="col-1"></div>
    </div>

    <div class="row mb-3">
      <div class="col-1"></div>
      <div class="col-10">
        <div class="form-group">
          <h6>Studio Name*:</h6>
          <br/>
          <%= f.text_field :name, placeholder: "Core Studio", class: "form-control no-border color-bottom-border", required: true %>
        </div>
       </div>
       <div class="col-1"></div>
    </div>

    <div class="row mb-3">
      <div class="col-1"></div>
      <div class="col-10">
        <div class="form-group">
          <h6>Address*:</h6>
          <br/>
          <%= f.text_field :location, placeholder: "15 Front St.", class: "form-control no-border color-bottom-border", required: true, id: :autocomplete_address %>
        </div>
       </div>
       <div class="col-1"></div>
    </div>

    <div class="row mb-3">
      <div class="col-1"></div>
      <div class="col-10">
        <div class="form-group">
          <h6>Phone:</h6>
          <br/>
          <%= f.text_field :phone, placeholder: "416-123-456", class: "form-control no-border color-bottom-border" %>
        </div>
       </div>
       <div class="col-1"></div>
    </div>

    <div class="row mb-3">
      <div class="col-1"></div>
      <div class="col-10">
        <div class="form-group">
          <h6>Studio Schedule URL:</h6>
          <br/>
          <%= f.text_field :website_url, placeholder: "example.com", class: "form-control no-border color-bottom-border" %>
        </div>
       </div>
       <div class="col-1"></div>
    </div>

    <div class="row mb-3">
      <div class="col-1"></div>
      <div class="col-10">
        <div class="form-group">
          <h6>Cover Photo:</h6>
          <br/>
          <%= f.file_field :avatar, class: "form-control no-border color-bottom-border" %>
        </div>
       </div>
       <div class="col-1"></div>
    </div>


    <div class="row">
      <div class="col-8"></div>
      <div class="col-3">
        <%= f.submit 'Save', class: 'btn btn-info' %>
      </div>
      <div class="col-1"></div>
    </div>

  <% end %>
</div>

<%= javascript_include_tag 'autocomplete', 'data-turbolinks-track': 'reload' %>

app/views/studios/edit.html.erb
<%= render 'layouts/navbar_edit' %>

<%= render 'form' %>

<div class="container my-5 text-center">
  <div class="row">
    <div class="col-12">
      <div class="form-group mt-3">
        <%= form_tag trainer_studios_url(@studio), method: :post do %>
          <%= select_tag 'trainer_id', options_from_collection_for_select(@trainers, 'id', "first_name") %>
          <%= hidden_field_tag "studio_id", @studio.id %>
          <%= submit_tag "Add", class:"btn btn-info" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/studios/index.html.erb
<%= render 'layouts/navbar_studios' %>

<div class="container text-left">
  <p class="text-center text-primary"><%= flash[:notice] %></p>

  <div class="row">
    <div class="col-12 mb-3 text-right">
      <h3><%= link_to "Create Studio", new_studio_path, class: "btn btn-info" %></h3>
    </div>
  </div>

  <div class="row">
    <div class="col-2"></div>
    <div class="col-6"><p>Studio Name</p></div>
    <div class="col-4"><p>Location</p></div>
  </div>

  <% @studios.each do |s| %>
    <div class="row mt-3 mb-3 pb-3 border-bottom">
      <div class="col-1 my-auto">
        <% if current_user && current_user.role == 8 %>
          <%= button_to "x", { action: "destroy", id: s.id },
            method: :delete, data: { confirm: "Are you sure?" },
            class: "btn btn-sm btn-danger" %>
        <% end %>
      </div>
      <div class="col-7 my-auto">
        <h5><%= link_to "#{s.name}", studio_url(s) %><h5>
        <p class="">@<%= s.username %></p>
      </div>
      <div class="col-3 my-auto">
        <%= s.location %>
      </div>
      <div class="col-1 my-auto">
        <%= link_to image_tag('edit.png', height: 11, width: 11, class:'text-right'), edit_studio_url(s) %>
      </div>
      <div class="divider"></div>
    </div>
  <% end %>

  <% if @studios.empty? %>
    <div class="row text-center">
      <div class="col-12">
        <h4 class="mt-3 mb-3">No studios found.</h4>
      </div>
    </div>
  <% end %>
</div>

<%= render 'layouts/footer' %>

app/views/studios/manage_trainers.html.erb
<%= render 'layouts/navbar_edit' %>
<!-- < Add/Edit Studio Trainrs -->

<div class="container my-5">
  <div class="row mb-8">
    <div class="col-2"></div>
    <div class="col-8">
      <%= form_tag trainer_studios_url(@studio), method: :post do %>
        <%= select_tag 'trainer_id', options_from_collection_for_select(@trainers, 'id', "first_name") %>
        <%= hidden_field_tag "studio_id", @studio.id %>
        <%= submit_tag "Add", class:"btn btn-info" %>
      <% end %>
    </div>
    <div class="col-2"></div>
  </div>
</div>

<div class="container">
  <div class="row text-center">
    <% @my.trainers.each do |trainr| %>
      <div class="col-1"></div>
      <div class="col-10">
        <div class="row text-center card-my-trainr">
          <div class="col-1"></div>
          <div class="col-1"></div>
          <div class="col-2">
            <%= link_to image_tag(trainr.img_url, class: "my-trainr-pic"), trainr.url %>
          </div>
          <div class="col-1"></div>
          <div class="col-5">
            <%= trainr.firstname %><%= trainr.lastname %>
            <br/><%= trainr.location %>
          </div>
          <div class="col-1"></div>
          <div class="col-1">
            <% if current_user.trainer %>
              <%= button_to "x", { action: "destroy", id: s.id },
                method: :delete, data: { confirm: "Are you sure?" },
                class: "btn btn-sm btn-danger" %>
            <% end %>
          </div>
        </div>
      </div>
      <div class="col-1"></div>
    <% end %>
  </div>
</div>

app/views/studios/managetrainers.html.erb
<%= render 'layouts/navbar_edit' %>
<!-- < Add/Edit Studio Trainrs -->

<div class="container my-5">
  <div class="row mb-8">
    <div class="col-2"></div>
    <div class="col-8">
      <!-- search & add -->
    </div>
    <div class="col-2"></div>
  </div>
</div>

<div class="container">
  <div class="row text-center">
    <% @my.trainers.each do |trainr| %>
      <div class="col-1"></div>
      <div class="col-10">
        <div class="row text-center card-my-trainr">
          <div class="col-1"></div>
          <div class="col-1"></div>
          <div class="col-2">
            <%= link_to image_tag(trainr.img_url, class: "my-trainr-pic"), trainr.url %>
          </div>
          <div class="col-1"></div>
          <div class="col-5">
            <%= trainr.firstname %><%= trainr.lastname %>
            <br/><%= trainr.location %>
          </div>
          <div class="col-1"></div>
          <div class="col-1">
            <%= image_tag("imagesx.gif", class: "x-icon") %>
            <!-- add logic to remove trainr on click -->
          </div>
        </div>
      </div>
      <div class="col-1"></div>
    <% end %>
  </div>
</div>

app/views/studios/new.html.erb
<%= render 'layouts/navbar_add_studio' %>

<%= render 'form' %>

app/views/studios/show.html.erb
<%= render 'layouts/navbar_studio_profile' %>

<div class="container text-center">
  <p class="text-primary mb-3"><%= flash[:notice] %></p>
  <p class="text-danger mb-3"><%= flash[:alert] %></p>

  <div class="row">
    <div class="col-12">
      <h1><%= @studio.name %></h1>
      <% if @studio.avatar.attachment.nil? %>
        <%= image_tag('milan.jpg', class:'round', height:'220', width:'320')%>
      <% else %>
        <%= image_tag @studio.avatar.service_url, class:'round mt-3 mb-3', height:'220', width:'320' %>
      <% end %>
      <p><%= @studio.location %></p>

      <!-- Show schedule times and days only if exist and gray out button if not -->
      <div class="buttons">
        <% if !@studio.website_url.nil? %>
          <% if !@studio.website_url.empty? %>
            <div class="row d-flex justify-content-center"><%= link_to image_tag('calendar.svg', class:'icon-link'), "https://#{@studio.website_url}", target: :_blank %></div>
          <% end %>
        <% end %>
      </div>

      <div class="color-bottom-border mt-3"></div>
    </div>
  </div>

  <div class="row mt-5">
    <div class="col-12">
      <h2 class="">Instructors</h2>
    </div>

    <% if !@studio.trainer_studios.empty? %>
      <% @studio.trainer_studios.each_with_index do |trainer_studio| %>
        <% trainr = User.find(trainer_studio.trainer_id) %>

        <div class="col-4">
          <% if trainr.avatar.attachment.nil? %>
        	  <%= image_tag('user.svg', class: "profile-pic-md") %>
          <% else %>
            <%= image_tag(trainr.avatar.service_url, class: "profile-pic-md") %>
          <% end %>
          <p class=""><%= "#{trainr.first_name} #{trainr.last_name}" %></p>
          <% if current_user && current_user.role == 8 %>
            <%= form_tag trainer_studio_url(trainer_studio.id), method: :delete do %>
              <%= submit_tag 'Remove', class:'btn btn-danger' %>
            <% end %>
          <% end %>
        </div>
      <% end %>
    <% else %>
      <div class="col-12">
        <p class="">No instructors found.</p>
      </div>
    <% end %>

    <div class="col-12">
      <div class="color-bottom-border mt-3"></div>
    </div>
  </div>

  <div class="row mt-5 mb-5">
    <div class="col-12">
      <% if !@studio.latitude.nil? && !@studio.longitude.nil? %>
        <p>
          <%= image_tag "https://maps.googleapis.com/maps/api/staticmap?zoom=17&size=400x300&markers=size:medium%7Ccolor:red%7C#{@studio.latitude},#{@studio.longitude}&key=#{ENV['GOOGLE_API_SERVER_KEY']}", alt: "Map" %>
        </p>
        <p>
          <%= @studio.location %>
        </p>
      <% end %>
    </div>
  </div>

  <%= render 'layouts/footer' %>
</div>

app/views/studios/trainrs.html.erb
<%= render 'layouts/navbar_edit' %>
<!-- < Add/Edit Studio Trainrs -->

<div class="container my-5">
  <div class="row mb-8">
    <div class="col-2"></div>
    <div class="col-8">
      <!-- search & add -->
    </div>
    <div class="col-2"></div>
  </div>
</div>

<div class="container">
  <div class="row text-center">
    <% @my.trainers.each do |trainr| %>
      <div class="col-1"></div>
      <div class="col-10">
        <div class="row text-center card-my-trainr">
          <div class="col-1"></div>
          <div class="col-1"></div>
          <div class="col-2">
            <%= link_to image_tag(trainr.img_url, class: "my-trainr-pic"), trainr.url %>
          </div>
          <div class="col-1"></div>
          <div class="col-5">
            <%= trainr.firstname %><%= trainr.lastname %>
            <br/><%= trainr.location %>
          </div>
          <div class="col-1"></div>
          <div class="col-1">
            <%= image_tag("imagesx.gif", class: "x-icon") %>
            <!-- add logic to remove trainr on click -->
          </div>
        </div>
      </div>
      <div class="col-1"></div>
    <% end %>
  </div>
</div>