config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  devise_for :users, controllers: {
    registrations: "users/registrations",
    confirmations: "users/confirmations"
  }

  get 'home' => 'users#home', as: :home
  get 'search' => 'users#index', as: :search
  root to: 'users#home'

  resources :users, only: [:show, :index, :edit, :update, :destroy], path: ''
  resources :studios
  resources :events, only: [:new, :create, :show, :edit, :update, :destroy]
  resources :offers, only: [:new, :create, :show, :edit, :update, :destroy]
  resources :after_signup
  resources :milestones, only: [:create, :edit, :update, :destroy]
  resources :certifications, only: [:create, :edit, :update, :destroy]
  resources :practice_categories, only: [:create, :index, :edit, :update, :destroy]
  resources :specialty_categories, only: [:create, :index, :edit, :update, :destroy]

  resources :user_practice_categories, only: [:create, :destroy]
  resources :user_specialty_categories, only: [:create, :destroy]
  resources :trainer_studios, only: [:create, :destroy]
  resources :user_studios, only: [:create, :destroy]

  resources :users, only: [:show], path: '' do
    resources :events, only: [:index]
    resources :offers, only: [:index]
    resources :trainer_studios
    resources :user_studios
    get 'profile' => 'users#profile', as: :profile
    get 'bio' => 'users#bio', as: :bio
    get 'edit_bio' => 'users#edit_bio', as: :edit_bio
    get 'my_trainers' => 'users#my_trainers', as: :my_trainers
    get 'manage_events' => 'events#manage_events', as: :manage_events
    get 'manage_offers' => 'offers#manage_offers', as: :manage_offers
  end

  get '/:friendly_id', to: 'users#show'

  resources :studios do
    resources :trainer_studios
    resources :user_studios
    get 'manage_trainers' => 'studios#manage_trainers', as: :manage_trainers
  end

  post 'landing_email' => 'users#landing_email', as: :landing_email
  get 'forgot_password' => 'users#forgot_password', as: :forgot_password
  get 'welcome' => 'users#welcome', as: :welcome
  get 'verification' => 'users#verification', as: :verification
  get 'manage_users' => 'users#manage_users', as: :manage_users
end

app/views/layouts/_footer.html.erb
<div class="mt-2">
  <% if !current_user %>
    <%= render 'layouts/footer_logged_out' %>
  <% elsif current_user.role == 0 %>
    <%= render 'layouts/footer_trainee' %>
  <% elsif current_user.role == 1 %>
    <%= render 'layouts/footer_trainer' %>
  <% elsif current_user.role == 8 %>
    <%= render 'layouts/footer_admin' %>
  <% end %>
</div>

app/views/layouts/_footer_admin.html.erb
<div class="bg-light fixed-bottom">
  <div class="container">
    <div class="row">
      <div class="col">
        <%= link_to home_url, class: "footer-link" do %>
          <%= image_tag("home.svg", width: "18", height: "18") %>
          <p class="mt-1 mb-1">Home</p>
        <% end %>
      </div>
      <div class="col">
        <%= link_to new_studio_url, class: "footer-link" do %>
          <%= image_tag("plus.svg", width: "8", height: "8") %>
          <p class="mt-1 mb-1">+Studio</p>
        <% end %>
      </div>
      <div class="col">
        <%= link_to practice_categories_url, class: "footer-link" do %>
          <%= image_tag("gear.svg", width: "8", height: "8") %>
          <p class="mt-1 mb-1">Practices</p>
        <% end %>
      </div>
      <div class="col">
        <%= link_to specialty_categories_url, class: "footer-link" do %>
          <%= image_tag("gear.svg", width: "8", height: "8") %>
          <p class="mt-1 mb-1">Specialties</p>
        <% end %>
      </div>
      <div class="col">
        <%= link_to manage_studios_url, class: "footer-link" do %>
          <%= image_tag("gear.svg", width: "8", height: "8") %>
          <p class="mt-1 mb-1">Studios</p>
        <% end %>
      </div>
      <div class="col">
        <%= link_to manage_users_url, class: "footer-link" do %>
          <%= image_tag("gear.svg", width: "8", height: "8") %>
          <p class="mt-1 mb-1">Users</p>
        <% end %>
      </div>
      <div class="col">
        <%= link_to admin_url, class: "footer-link" do %>
          <%= image_tag("gear.svg", width: "8", height: "8") %>
          <p class="mt-1 mb-1">Admin</p>
        <% end %>
      </div>
      <div class="col">
        <%= link_to user_url(current_user), class: "footer-link" do %>
          <%= image_tag("finger-print.svg", width: "8", height: "8") %>
          <p class="mt-1 mb-1">Profile</p>
        <% end %>
      </div>
    </div>
  </div>
</div>

<div class="col">
  <%= link_to user_my_trainers_url(current_user), class: "footer-link" do %>
    <%= image_tag("speed.svg", width: "18", height: "18") %>
    <p class="mt-1 mb-1">Trainrs</p>
  <% end %>
</div>

app/views/layouts/_footer_logged_out.html.erb
<div class="bg-light fixed-bottom" id="trainer-footer">
  <div class="container my-auto">
    <div class="row">
      <div class="col">
        <%= link_to home_url, class: "footer-link" do %>
          <%= image_tag("home.svg", width: "18", height: "18") %>
          <p class="mt-1 mb-1">Home</p>
        <% end %>
      </div>
      <div class="col">
        <%= link_to search_url, class: "footer-link" do %>
          <%= image_tag("search.svg", width: "18", height: "18") %>
          <p class="mt-1 mb-1">Search</p>
        <% end %>
      </div>
      <div class="col">
        <%= link_to new_user_session_url, class: "footer-link" do %>
          <%= image_tag("finger-print.svg", width: "18", height: "18") %>
          <p class="mt-1 mb-1">Log In</p>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_logged_out.html.erb
<%= render 'layouts/navbar_home_logged_out' %>

<div class="container text-center">
  <p class="mb-5"><%= flash[:notice] %></p>
  <p class="mb-5"><%= flash[:alert] %></p>

  <div class="row mb-4">
    <div class="col-12">
      <!-- Phone image with scroll displaying app -->
      <p>Own your profile. In minutes. For Free.</p>
      <%= image_tag("example.png", width: 175, height: 350)%>
    </div>
  </div>
  <div class="row mt-5 mb-5">
    <div class="col-12">
      <%= form_tag(users_url, method: "get", id: "search", class:"form-inline my-2 my-lg-0") do %>
        <%= text_field_tag :search, params[:search], placeholder: "Search by name or studio", required: true, class: "form-control mr-sm-2 ml-auto", style: "width: 200px;" %>
        <%= submit_tag "Go", class:"btn btn-outline-success my-2 my-sm-0 mr-auto" %>
      <% end %>
    </div>
  </div>
  <div class="row mb-4">
    <div class="col-4"></div>
    <div class="col-4">
      <%= link_to "Sign Up", new_user_registration_url, class:'btn btn-info btn-block round-btn' %>
    </div>
    <div class="col-4"></div>
  </div>
  <div class="row mb-4">
    <div class="col-4"></div>
    <div class="col-4">
      <%= link_to "Log In", new_user_session_url, class:'btn btn-outline-info btn-block round-btn' %>
    </div>
    <div class="col-4"></div>
  </div>
  <div class="row mb-5">
    <div class="col-12">
      <p>mvmt.bio 2020</p>
    </div>
  </div>
  <!-- Use a better way to stop footer overlapping content later -->
  <div style="height: 150px;"></div>
</div>

app/views/layouts/_navbar_add_class.html.erb
<nav class="navbar navbar-light mt-3 mb-5">
  <div class="col-3">
    <%= link_to image_tag("back.jfif", height:'13', width:'18' ), :back %>
  </div>
  <div class="col-6 text-center">
    <h1 class="ml-auto mr-auto my-auto branding main">Add New Class</h1>
  </div>
  <div class="col-3"></div>
</nav>

app/views/layouts/_navbar_edit.html.erb
<div class="container mt-3 mb-5">
  <div class="col-3">
    <%= link_to image_tag("back.jfif", height:'13', width:'18' ), user_url(current_user) %>
  </div>
  <div class="col-6 text-center">
    <h1 class="ml-auto mr-auto my-auto branding main">Edit</h1>
  </div>
  <div class="col-3"></div>
</div>

app/views/layouts/_navbar_home.html.erb
<nav class="navbar navbar-expand-lg navbar-light mt-4 mb-2">
  <h1 class="ml-auto mr-auto my-auto branding main">mvmt.bio</h1>
</nav>

app/views/layouts/_navbar_home_logged_out.html.erb
<nav class="navbar navbar-expand-lg navbar-light mt-3 mb-2">
  <h1 class="ml-auto mr-auto my-auto branding main">mvmt.bio</h1>
</nav>

app/views/layouts/_navbar_logged_out_trainer_profile.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light mb-5">
  <h1><a class="navbar-brand" href="/">t</a></h1>
  <ul class="navbar-nav ml-auto mr-auto my-auto">
    <h1>trainer.bio/<%= @user.username %></h1>
  </ul>
  <ul class="navbar-nav">
    <li class="nav-item">
      <%= link_to "Sign Up", new_user_registration_url, class:"nav-link" %>
    </li>
    <li class="nav-item">
      <%= link_to "Log In", new_user_session_url, class: "nav-link" %>
    </li>
  </ul>
</nav>

app/views/layouts/_navbar_profile.html.erb
<div class="container">
  <div class="row text-center mb-2 mt-4 branding main">
    <div class="col-2"></div>
    <div class="col-8">
      <h1 class="nav-user">mvmt.bio /
        <% if !@user.username.nil? %>
          <%=@user.username%>
        <% end %>
      </h1>
    </div>
    <div class="col-2"></div>
  </div>
</div>

app/views/layouts/_navbar_public_trainer_profile.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light mb-5">
  <h1><a class="navbar-brand" href="/">t</a></h1>
  <ul class="navbar-nav ml-auto mr-auto my-auto branding main">
    <h1>trainer.bio/<%= @user.username %></h1>
  </ul>
  <ul class="navbar-nav">
    <li class="nav-item">
      <%= link_to "Send Msg", class:"nav-link" %>
    </li>
  </ul>
</nav>

app/views/layouts/_navbar_registration.html.erb
<nav class="navbar navbar-light mt-3 mb-5">
  <div class="col-3">
    <%= link_to image_tag("back.jfif", height:'13', width:'18' ), home_url %>
  </div>
  <div class="col-6 text-center">
    <h1 class="ml-auto mr-auto mt-1 branding main my-auto">mvmt.bio</h1>
  </div>
  <div class="col-3"></div>
</nav>

app/views/layouts/_navbar_search_results_logged_in.html.erb
<div class="container text-center">
  <div class="row my-3">

    <div class="col-12">
      <%= form_tag(users_url, method: "get", id: "search") do %>
        <%= text_field_tag :search, params[:search], placeholder: "Search Name or Studio", required: true  %>
        <%= submit_tag "Go", class:"btn btn-outline-info btn-sm" %>
      <% end %>
    </div>

  </div>
</div>